import type { Metadata } from "next";
import "./globals.css";
import { ApiProvider } from "@reduxjs/toolkit/query/react";
import { StoreProvider } from "./store/StoreProvider";

export const metadata: Metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoreProvider>
  );
}
